FIND_PATH(LAPACK_INCLUDE_DIR NAMES clapack.h
      PATHS
      ${CMAKE_SOURCE_DIR}/include
      ${CMAKE_SOURCE_DIR}/../include
      ${CMAKE_INSTALL_PREFIX}/include
      ${KDE4_INCLUDE_DIR}
      PATH_SUFFIXES CLAPACK
      )
MARK_AS_ADVANCED(LAPACK_INCLUDE_DIR)

if (LAPACK_LIBRARIES)
  set (LAPACK_FIND_QUIETLY TRUE)
endif (LAPACK_LIBRARIES)

find_library (LAPACK_LIBRARIES
  lapack
  HINTS
  LAPACK_LIB
  $ENV{LAPACK_LIB}
  ${LIB_INSTALL_DIR}
  )

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(LAPACK DEFAULT_MSG LAPACK_INCLUDE_DIR LAPACK_LIBRARIES)

mark_as_advanced (LAPACK_LIBRARIES)

IF(LAPACK_FOUND)
  SET(LAPACK_INCLUDE_DIRS ${LAPACK_INCLUDE_DIR})
ELSE(LAPACK_FOUND)
  SET(LAPACK_INCLUDE_DIRS)
ENDIF(LAPACK_FOUND)

